### ISSUE TITLE
pTraits tests not passing

### ISSUE THREAD

**Issue by saifthe1** [saifmulla/OpenFOAM-Windows#3]
The pTraits class is implemented to create a specialised template, until now there is no definite way to write a proper test therefore temporally tests are left blank to pass. However before merge ensure tests pass for this class.

**Comment by saifmulla** [comment]
PTraits class behaves like a base class for all primitive types there all instances of primitives must implement inside pTraits, therefore after implementing primitives classes with pTraits the tests passes as a result this fixes issue #3
